#
# react-app
# https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11437072#notes
#

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app

      # -v /home/node/app/node_modules -v $(pwd):/home/node/app

  tests: # second service just for tests - surprise
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
